services:
  hyperf-skeleton:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
      args:
        INSTALL_XDEBUG: ${INSTALL_XDEBUG:-true}
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false  
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root        # senha do root
      MYSQL_DATABASE: albion             # nome do banco que será criado automaticamente
      MYSQL_USER: albion               # usuário adicional (opcional)
      MYSQL_PASSWORD: albion           # senha do usuário (opcional)
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    name: hyperf-skeleton
